######################################################################
# Automatically generated by qmake (2.01a) Sat May 14 19:29:39 2011
######################################################################

CONFIG = console

DEFINES += SQLITE_ENABLE_COLUMN_METADATA SQLITE_ENABLE_FTS3 SQLITE_ENABLE_FTS3_PARENTHESIS

TEMPLATE = app
TARGET = test
DEPENDPATH += .
INCLUDEPATH += .
INCLUDEPATH += ../src/sqlite

# Input
SOURCES += test.cpp ../src/sqlite/sqlite3.c
