######################################################################
# Automatically generated by qmake (2.01a) Mon Apr 4 19:25:58 2011
######################################################################

CONFIG = console

DEFINES += SQLITE_ENABLE_FTS3 SQLITE_ENABLE_FTS3_PARENTHESIS

TEMPLATE = app
TARGET = sqlite3
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += sqlite3.h sqlite3ext.h
SOURCES += shell.c sqlite3.c
